# Generated by Django 5.1.1 on 2024-09-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=250)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
